### ISSUE TITLE
Make "profiler" available

### ISSUE THREAD

**Issue by Grummfy** [auraphp/Aura.Cli_Kernel#11]
Hi,
I think it could be helpful to have the possibilities to add a profiler in the CliKernel.

Example of usage:
- getting the time to execute a command
- getting the memory taken by a command
- getting some other information

What do you think about this?

**Comment by mbrevda** [comment]
Instead of simply prefixing the command with `time`?

**Comment by Grummfy** [comment]
Time is only for time and nothing else, and make your live more complicated to get the result in php and do something with the value. By the way it works only on unix system.

**Comment by mbrevda** [comment]
I sense that you're not just looking to time the specific job, you want to be able to profile the steps (a la aura.sql)?

**Comment by Grummfy** [comment]
exactly.
Perhaps not so advanced than profiler in aura

**Comment by mbrevda** [comment]
Unlike sql, where the commands are the bane of the project, I feel that a profiler for commands in cli would be better suited implemented by some external mechanism, abstracted from cli, and not by the project itself.

**Comment by pmjones** [comment]
> I feel that a profiler for commands in cli would be better suited implemented by some external mechanism

I have to agree with @mbrevda here. Having said that, @Grummfy , if you have an implementation or example of what you'd like to have done, I'll be happy to review it.
