### ISSUE TITLE
Help for Hello Command

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Cli_Kernel#3]
Running 

```
php cli/console.php help hello doesn't have any information .
```

As the help itself is a test command, may be the way the help for hello command will be like 

```
php cli/console.php hello --help
```

Normally this is the way I expected a command to show. Not sure how this will become.

**Comment by pmjones** [comment]
I don't think we want a `--help` option on the `hello` command, but I can get behind adding help for it as an example for `Aura\Cli\Help`.

**Comment by pmjones** [comment]
Fixed as part of Cli_Project: https://github.com/auraphp/Aura.Cli_Project/commit/a3d34a341cd4b099f12536eea6a61cb683d86222
