### ISSUE TITLE
we could remove the Aura.Project_Kernel dependency

### ISSUE THREAD

**Issue by cordoval** [auraphp/Aura.Cli_Kernel#7]
Aura.Cli_Kernel has a very weak and non-production dependency on Aura.Project_kernel

this can be easily removed because it is only used in Factory to create a container which imo is not really meriting a dependency. The reason why i think is good to remove the dependency is that it will give more clarity in ho Cli is very independent and decoupled on its own. I believe Aura has one of the best decoupled console cli packages and I think this can help a lot in the understanding of things. The factory is being used only in a functional test which imo can just be replaced with the logic of the method easily.

**Comment by harikt** [comment]
@cordoval I believe the project kernel makes the web and cli work the same way.

**Comment by cordoval** [comment]
the console uses the Factory but that can just be replaced and the dependency removed, I will do so on my personal projects, for now this can stay as it is. :grin:
